global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']  
